spring:
  application:
    name:
  web:
    error:
      include-stacktrace:

  servlet:
    multipart:
      max-file-size:
      max-request-size:

  # MySQL
  datasource:
    url:
    username:
    password:
    driver-class-name:

# MyBatis
mybatis:
  mapper-locations:
  type-aliases-package:

# Log
logging:
  file:
    # 로그 파일 경로
    name:
  level:
    # 로그 출력 레벨 설정 (trace, debug, info, info, warn, error)
    root:

    # 특정 패키지만 로그 출력 레벨 설정
    com.msa4meerkatgram.controllers:

# Security & JWT
security:
  jwt:
    secure:
    issuer:
    type:
    access-token-expiry:
    refresh-token-expiry:
    refresh-token-cookie-name:
    refresh-token-cookie-expiry:
    secret:
    header-key:
    scheme:
    reiss-uri:

# file
file:
  server-uri:
  storage-path:
  profile-path:
  post-path:
  allow-extension-list:

cors:
  allowed-origins:
  max-age:
